version: "3.8"
services:
  devcontainer:
    network_mode: host
    image: devcontainer
    container_name: devcontainer-gpu
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_NAME=vscode
        - USER_UID=1000
        - USER_GID=1000
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh/:/home/vscode/.ssh
      - $HOME/.gitconfig:/home/vscode/.gitconfig
    command: /bin/sh -c "while sleep 1000; do :; done"
    privileged: true
    
